# Generated by Django 2.2 on 2020-05-28 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=30, unique=True)),
                ('area_remark', models.CharField(max_length=100)),
                ('is_delete', models.CharField(default='N', max_length=1)),
                ('is_tmp', models.CharField(default='N', max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(max_length=30, unique=True)),
                ('dpt_parent_sys_id', models.CharField(max_length=36)),
                ('dpt_desc', models.CharField(max_length=100)),
                ('is_delete', models.CharField(default='N', max_length=1)),
                ('is_tmp', models.CharField(default='N', max_length=1)),
                ('dpt_manager_id', models.CharField(max_length=36)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_sex_id', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('emp_dpt_id', models.CharField(max_length=30)),
                ('emp_status_id', models.CharField(max_length=30)),
                ('emp_birthday', models.DateTimeField(verbose_name='birthday date')),
                ('emp_id_no', models.CharField(max_length=20, unique=True)),
                ('emp_remark', models.CharField(max_length=100)),
                ('emp_card_type', models.IntegerField(default=0)),
                ('emp_pwd', models.CharField(max_length=256)),
                ('is_delete', models.CharField(default='N', max_length=1)),
                ('is_tmp', models.CharField(default='N', max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Empcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_serial_no', models.CharField(max_length=20, unique=True)),
                ('card_fix_id', models.CharField(max_length=36, unique=True)),
                ('card_onwer_no', models.CharField(max_length=20)),
                ('card_due_day', models.DateTimeField(verbose_name='due date')),
                ('card_type_id', models.CharField(max_length=20)),
                ('card_status_id', models.CharField(max_length=20)),
                ('card_remark', models.CharField(max_length=100)),
                ('card_pwd', models.CharField(max_length=256)),
                ('is_tmp', models.CharField(default='N', max_length=1)),
                ('is_delete', models.CharField(default='N', max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
